public enum Tipo_ataque {
    // example attacks
    FIREBALL, WATERGUN, THUNDERBOLT, TACKLE, SCRATCH, BITE, SLASH, PUNCH, KICK, 
    HEADBUTT, BODYSLAM, HYPERBEAM, PSYCHIC, SHADOWBALL, DRAGONCLAW, EARTHQUAKE, 
    ICEBEAM, BLIZZARD, SOLARBEAM, HYDROPUMP, THUNDER, FIREBLAST, FLAMETHROWER, SURF, 
    ICEPUNCH, THUNDERPUNCH, FIREPUNCH

}
