public enum Tipo_ataque_pokemon {
    // example attacks types
    FIREBALL, WATERGUN, THUNDERBOLT, TACKLE, SCRATCH, BITE, SLASH, PUNCH, KICK, 
    HEADBUTT, BODYSLAM, HYPERBEAM, PSYCHIC, SHADOWBALL, DRAGONCLAW, EARTHQUAKE, 
    ICEBEAM, BLIZZARD, SOLARBEAM, HYDROPUMP, THUNDER, FIREBLAST, FLAMETHROWER, SURF, 
    ICEPUNCH, THUNDERPUNCH, FIREPUNCH, NORMAL, FIRE, WATER, ELECTRIC, GRASS, ICE, FIGHTING, POISON, GROUND, FLYING,
     BUG, ROCK, GHOST, DRAGON, DARK, STEEL, FAIRY

}
