public enum Tipo_ataque_pokemon {
    // tipos de ataques de ejemplo
    BOLA_DE_FUEGO, PISTOLA_DE_AGUA, RAYO, PLACAJE, ARAÑAZO, MORDISCO, CORTE, PUÑETAZO, PATADA, 
    CABEZAZO, GOLPE_CUERPO, HIPERRAYO, PSIQUICO, BOLA_SOMBRA, GARRA_DRAGON, TERREMOTO, 
    RAYO_HIELO, VENTISCA, RAYO_SOLAR, HIDROBOMBA, TRUENO, LLAMARADA, LANZALLAMAS, SURF, 
    PUÑO_HIELO, PUÑO_TRUENO, PUÑO_FUEGO, NORMAL, FUEGO, AGUA, ELECTRICO, PLANTA
}
